# -*- mode: ruby -*-
# vi: set ft=ruby :

##### DEFINITION #####

VAGRANTFILE_API_VERSION = "2"

##### REQUIREMENT #####

# need /vagrant/id_rsa_gituser
# need /vagrant/id_rsa_gituser.pub
# need /vagrant/id_rsa_devuser
# need /vagrant/id_rsa_devuser.pub

##### INLINE SCRIPT START #####

$script = <<SCRIPT
# N/A
SCRIPT

##### CONFIGURATION #####

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos6"
  config.vm.box_url = "http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.4-i386-v20130731.box"
  config.vm.define :dev do |host|
    host.vm.hostname = "dev"
    host.vm.network :private_network, ip: "172.20.10.11"
    host.vm.provision :shell, path: "setup.sh", args: [ "/vagrant" ]
    host.vm.provision :shell, inline: $script
  end
end

